image: debian:unstable
 
before_script:
  - apt update -qq
  - apt install -y -qq build-essential 
stages:
  - build
 
# FIXME: Re-enable valgrind once running the tests under it doesn’t take forever (it causes timeouts).
# Re-add valgrind to apt-install line above
build-distcheck:
  stage: build
  script:
    - mkdir build
    - cd build
    - cmake ..
    - make
 
  # The files which are to be made available in GitLab
  artifacts:
    paths:
      - build/*